FROM adoptopenjdk/openjdk11:alpine-jre

COPY target/simple-springboot-service-0.0.1-SNAPSHOT.jar .

ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","simple-springboot-service-0.0.1-SNAPSHOT.jar"]

