FROM adoptopenjdk/openjdk11:alpine-slim as builder
WORKDIR /app
COPY . .
RUN ./mvnw clean package -DskipTests

FROM adoptopenjdk/openjdk11:alpine-jre
COPY --from=builder /app/target/simple-springboot-service-0.0.1-SNAPSHOT.jar /
ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","/simple-springboot-service-0.0.1-SNAPSHOT.jar"]

