FROM adoptopenjdk/openjdk11:alpine-slim

WORKDIR /app
COPY . .
RUN ./mvnw clean package -DskipTests

ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","/app/target/simple-service-0.0.1-SNAPSHOT.jar"]

