server:
  port: 8080

# management:
#   server:
#     port: 8081

spring:
  jmx:
    enabled: false

dateService:
  url: localhost:8081

logging:
  level:
    ROOT: INFO
    com.keyholesoftware.devops: DEBUG